services:
  - type: web
    name: job-portal
    env: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p data
      cp consolidated_jobs_*.xlsx data/ || true
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: FLASK_ENV
        value: production 