services:
  - type: web
    name: jobalert
    env: python
    buildCommand: chmod +x deploy.sh && ./deploy.sh
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
    routes:
      - type: rewrite
        source: /*
        destination: / 